.\"                              hey, Emacs:   -*- nroff -*-
.\" xjadeo is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH XJADEO 1 "October 29, 2005"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
xjadeo \- jack video monitor
.SH SYNOPSIS
.B xjadeo
.RI [ options ] videofile
.SH DESCRIPTION
\fBxjadeo\fP is a very simple video player that gets sync from jack.
.PP
When a jack-client like Muse, Rosegarden or Ardour acts as a timebase master, xjadeo will display the video frame in sync with jack transport.
xjadeo renders the video using Imlib, and therefore only supports video-codecs that are supported by the local Imlib installation! (see below on how to re-encode the file)
.PP
xjadeo allows you to resize the image on the fly, adding an additional performance penalty.

Pressing Mouse button 1 - will resize the monitor window to the original video size.
Mouse button 2 and 3 resize the window to match the file aspect ratio.
The Scroll Wheel (button 4,5) stepwise decreases / increases the window size - maintaining the original aspect ratio.
Use the Window Manager kill button or CTRL-C  to quit xjadeo.
.SH USAGE
First you have to encode your video file to a certain specific format. For this I use the utility mencoder that comes with mplayer. The appropriate spell is:

  mencoder -idx -ovc lavc -lavcopts keyint=1 -nosound input-file.xxx -o output-file.avi
  
This creates from your input-file.xxx an AVI mpeg4 encoded video file with no sound, an index (-idx) and no compression between frames (every frame is a key frame). The file thus can become really BIG, so watch out your disk space. 

You may also want to shrink the size of the frame by adding the option -vf scale=width:height. This will reduce the size of the avi file, will tax less the system resources when displayed and will leave more space in the screen for your audio software. Usually I find 160:120 enough, but depending on the size of your screen and hard disk and the power of your computer, you may want to have a bigger display. 

Then you have to be sure that jackd is running.

Finally, run xjadeo with the following command:

  xjadeo [options] output-file.avi &
.SH OPTIONS
\fBxjadeo\fP accepts the following options:
.TP
\.B -q , --quiet, --silent
Inhibit usual output.
.TP
\.B -v, --verbose
Print more information.
.TP
\.B -k, --keyframes
Seek only to keyframes of the video. (improves performance)
.TP
\.B -t, --try-codec
Check if the given video file can be played by xjadeo.
No window is opened in this mode.
The program exits with code 1 if the file format is not supported. 
.TP
\.B -f, --fps 
How often xjadeo updates the screen. The default is 10 fps (not the video files default)!
.TP
\.B -h, \-\-help
Show a summary of the available options.
.TP
\.B -V, \-\-version
Show the version of program.
.TP
\.B -o --offset
Time offset in video-frames. There is a machine-dependent time lag 
between jack transport and video display. This option allows to 
compensate for it.
.\" .SH "SEE ALSO"
.\" .BR jack (1), 
.SH AUTHORS
Luis Garrido <luisgarrido@users.sourceforge.net>,
Robin Gareus <robin@gareus.org>.
