'\" t
.\"     Title: qjadeo
.\"    Author: Robin Gareus <robin@gareus.org>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 07/04/2011
.\"    Manual: Manual Pages
.\"    Source: http://xjadeo.sf.net 0.6.X
.\"  Language: English
.\"
.TH "QJADEO" "1" "07/04/2011" "http://xjadeo\&.sf\&.net 0\&.6" "Manual Pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
qjadeo \- GUI front\-end to \fBxjadeo\fR
.SH "SYNOPSIS"
.HP \w'\fBqjadeo\fR\ 'u
\fBqjadeo\fR
.SH "DESCRIPTION"
.PP
Xjadeo
is a software video player that displays a video\-clip in sync with an external time source (MTC, LTC, JACK\-transport)\&.
.PP
\fBqjadeo\fR
is a graphical front\-end to
Xjadeo\&. It communicates with
Xjadeo
either directly (single session) or using
\fBxjremote\fR\&.
.SH "ENVIRONMENT"
.PP
If the
\fBXJREMOTE\fR
variable is set,
qjadeo
will assume that it holds the path to the
\fBxjremote\fR
executable\&.
.SH "SEE ALSO"
.PP
xjadeo(1)
.PP
xjremote(1)
.SH "AUTHORS"
.PP
\fBRobin Gareus\fR <\&robin@gareus.org\&>
.RS 4
linuxaudio.org
.RE
.PP
\fBLuis Garrido\fR <\&luisgarrido@users.sourceforge.net\&>
.RS 4
luisgarrido.users.sourceforge.net
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2005, 2006, 2007, 2009, 2010 Robin Gareus, Luis Garrido
.br
