'\" t
.\"     Title: qjadeo
.\"    Author: Robin Gareus
.\" Generator: DocBook XSL Stylesheets v1.75.0 <http://docbook.sf.net/>
.\"      Date: 05/29/2009
.\"    Manual: Manual Pages
.\"    Source: http://xjadeo.sf.net 0.4.X
.\"  Language: English
.\"
.TH "QJADEO" "1" "05/29/2009" "http://xjadeo\&.sf\&.net 0\&.4" "Manual Pages"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
qjadeo \- GUI front\-end to \fBxjadeo\fR
.SH "SYNOPSIS"
.HP \w'\fBqjadeo\fR\ 'u
\fBqjadeo\fR
.SH "DESCRIPTION"
.PP
\fBxjadeo\fR
displays a video clip in sync with an external time source\&. It is a handy tool to help with the synchronization of the soundtrack of a video file\&.
\fBqjadeo\fR
is a graphical frontend to xjadeo\&. It communicates with xjadeo either directly (single session) or using xjremote\&.
.SH "ENVIRONMENT"
.PP
If the XJREMOTE variable is set, qjadeo will assume that it holds the path to the xjadeo/xjremote executable\&.
.SH "SEE ALSO"
.PP
xjadeo(1)
.PP
xjremote(1)
.SH "AUTHOR"
.PP
\fBRobin Gareus\fR
.RS 4
linuxaudio.org
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2005, 2006, 2007, 2009 Robin Gareus, Luis Garrido
.br
