.TH qjadeo 1 "April 22, 2006"  
.SH NAME
qjadeo \- GUI front\-end to xjadeo remote mode.
.SH SYNOPSIS
\fBqjadeo\fR [videofile]


xjadeo displays a video clip in sync with an
external timing source. It is a handy tool to help with the
synchronization of the soundtrack of a video file.
xjadeo supports different video file formats, video
output libraries and sync sources.


qjadeo if the XJADEO variable is set, qjadeo
will assume that it holds the path to the xjadeo executable.

