'\" t
.\"     Title: xjadeo
.\"    Author: Robin Gareus <robin@gareus.org>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/19/2010
.\"    Manual: Manual Pages
.\"    Source: http://xjadeo.sf.net 0.6.X
.\"  Language: English
.\"
.TH "XJADEO" "1" "11/19/2010" "http://xjadeo\&.sf\&.net 0\&.6" "Manual Pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xjadeo \- display a video\-clip in sync with an external time source
.SH "SYNOPSIS"
.HP \w'\fBxjadeo\fR\ 'u
\fBxjadeo\fR [\-aAbcCDhIkKlLnNPqQRsStvV] [\-d\ \fI<midi\-driver>\fR] [\-f\ \fI<fps>\fR] [\-F\ \fI<fps>\fR] [\-i\ \fI<int>\fR] [\-m\ \fI<midi\-port>\fR] [\-M\ \fI<num>\fR] [\-o\ \fI<frames|SMPTE>\fR] [\-O\ \fI<osc\-port>\fR] [\-W\ \fI<rpc\-id>\fR] [\-x\ \fI<dpy\-mode>\fR] \fI<videofile>\fR
.HP \w'\fBxjadeo\fR\ 'u
\fBxjadeo\fR \-R [options] [\fI<videofile>\fR]
.HP \w'\fBxjadeo\fR\ 'u
\fBxjadeo\fR \-Q [options] [\fI<videofile>\fR]
.SH "DESCRIPTION"
.PP
Xjadeo
is a software video player that displays a video\-clip in sync with an external time source (MTC, LTC, JACK\-transport)\&.
.PP
It has applications in soundtrack composition, video monitoring or any task that requires synchronizing movie frames with audio events\&.
.PP
Xjadeo
supports different video file formats, video output libraries and sync sources\&.
.SH "OPTIONS"
.PP
\fB\-a\fR, \fB\-\-ontop\fR
.RS 4
Start
Xjadeo
\*(Aqalways\-on\-top\*(Aq of other windows (this option requires support from your window manager)\&.
.RE
.PP
\fB\-A\fR, \fB\-\-avverbose\fR
.RS 4
Enable verbose ffmpeg messages (format/codec debugging)\&.
.RE
.PP
\fB\-b\fR, \fB\-\-letterbox\fR
.RS 4
Retain aspect ratio and draw a letterbox around the video\-frame if necessary\&.
.RE
.PP
\fB\-c\fR, \fB\-\-no\-midiclk\fR
.RS 4
Do not use MIDI quarter\-frames for more exact sync\&.
.RE
.PP
\fB\-c\fR, \fB\-\-midiclk\fR
.RS 4
Use MIDI quarter\-frame timing for more exact sync (this is enabled by default since version 0\&.4\&.11)\&.
.RE
.PP
\fB\-d \fR\fB\fI<midi\-driver>\fR\fR, \fB\-\-midi\-driver \fR\fB\fI<midi\-driver>\fR\fR\fB \fR
.RS 4
Choose MIDI back\-end to use\&.
\fI<midi\-driver>\fR
can be either one of "JACK", "ALSA" or "portmidi" \- depending on the operating\-System and compile\-time configuration\&.
.RE
.PP
\fB\-D, \-\-debug\fR, \fB\-\-debug\fR
.RS 4
Enable debug mode\&. Print development related information\&.
.RE
.PP
\fB\-f \fR\fB\fI<n>\fR\fR, \fB\-\-fps \fR\fB\fI<n>\fR\fR
.RS 4
Desired refresh\-rate of the video display in frames per second\&. Non\-integer values are possible\&. Default: \-1\&.
.sp
If this value is set to zero (or less),
Xjadeo
will use the FPS of the video\-file as its screen update frequency\&.
.RE
.PP
\fB\-F \fR\fB\fI<n>\fR\fR, \fB\-\-filefps \fR\fB\fI<n>\fR\fR
.RS 4
Override the (auto\-detected) frame\-rate of the video\-file\&.
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Prints usage help and exits\&.
.RE
.PP
\fB\-i \fR\fB\fI<n>\fR\fR, \fB\-\-info \fR\fB\fI<n>\fR\fR
.RS 4
Displays information using the OSD (on\-screen display\&.)
.PP
\fB0\fR
.RS 4
Off\&.
.RE
.PP
\fB1\fR
.RS 4
Frame number\&.
.RE
.PP
\fB2\fR
.RS 4
SMPTE time code\&.
.RE
.PP
\fB3\fR
.RS 4
Both frame number and SMPTE\&.
.RE
.sp
The remote control interface allows more complete control over the OSD\&.
.RE
.PP
\fB\-I\fR, \fB\-\-ignorefileoffset\fR
.RS 4
This option is only useful for video files with a start\-offset, such as split vob files\&. Per default
Xjadeo
will honor offsets specified in the video\-file header and the file\*(Aqs PTS/DTS\&.
\fB\-I\fR
allows you to override and subtract this offset and makes the file start at SMPTE position 00:00:00:00 (although you can archive the same result, this option is not related to
\fB\-o\fR\&.)
.RE
.PP
\fB\-k\fR, \fB\-\-keyframes \fR
.RS 4
Instructs the internal algorithm to seek only to key\-frames\&. This option may improve the performance for certain video encodings\&.
.sp
The default behavior (without
\fB\-k\fR
and
\fB\-K\fR
arguments) is to search any ANY frame\&.
.RE
.PP
\fB\-K\fR, \fB\-\-continuous \fR
.RS 4
Decode video frame by frame starting from previous key\-frame\&. This particularly useful for reading files where not every frame is a key\-frame at the cost of increased CPU usage\&. Note that this option adds some extra latency when seeking\&. Combine it with
\fB\-f \-1\fR: it makes sense to set
Xjadeo\*(Aqs screen\-update frequency to match the frame\-rate of the video file\&.
.RE
.PP
\fB\-l\fR, \fB\-\-ltc\fR
.RS 4
Use LTC as sync\-source instead of JACK\-transport\&.
.RE
.PP
\fB\-L\fR, \fB\-\-nolash\fR
.RS 4
Disable LASH support\&.
.RE
.PP
\fB\-m \fR\fB\fI<midi\-port>\fR\fR, \fB\-\-midi \fR\fB\fI<midi\-port>\fR\fR
.RS 4
Get sync from MTC (MIDI Time Code) instead of JACK or LTC\&.
.sp
If using JACK\-MIDI driver,
\fI<midi\-port>\fR
is the JACK\-MIDI port to use as input \- use an empty value ("") to not auto\-connect
.sp
If using ALSA MIDI back\-end,
\fI<midi\-port>\fR
is the ALSA sequencer\-id to be used as the MTC source\&. A value of \-1 will leave
Xjadeo
unconnected\&.
.sp
If using portmidi,
\fI<port>\fR
is the port\-number of the MIDI input device to use\&. The value \-1 will attempt auto\-connect\&. Use
\fB\-v \-m \-1\fR
to list MIDI ports during auto\-detection\&.
.RE
.PP
\fB\-M \fR\fB\fI<n>\fR\fR, \fB\-\-midifps \fR\fB\fI<n>\fR\fR
.RS 4
Conversion between MTC SMPTE and frame number\&.
.PP
\fB0\fR (default)
.RS 4
Use MTC clock frame rate\&.
.RE
.PP
\fB1\fR
.RS 4
Use video\-file\*(Aqs frame\-rate\&.
.RE
.PP
\fB1\fR
.RS 4
Resample video frame rate / MTC\&.
.RE
.RE
.PP
\fB\-n\fR, \fB\-\-nodropframes\fR
.RS 4
Prevent
Xjadeo
from detecting drop\-frame\-timecode (usually files with 29\&.97 fps)
.RE
.PP
\fB\-N\fR, \fB\-\-dropframes\fR
.RS 4
Force
Xjadeo
to use drop\-frame\-timecode (drop\-frame\-timecode is only valid for files with 29\&.97 fps but your milage may vary)
.RE
.PP
\fB\-o \fR\fB\fI<n>\fR\fR, \fB\-\-offset \fR\fB\fI<n>\fR\fR
.RS 4
Offset the video playback a certain number of (video) frames relative to the sync master time base\&. Admits negative values\&.
\fI<n>\fR
can be specified either as integer frame\-number or SMPTE text\&.
.RE
.PP
\fB\-P\fR, \fB\-\-genpts\fR
.RS 4
This option passed on to ffmpeg and has no effect on older versions of libavformat\&.
.sp
it can be used to generate "presentation time stamps" if they are missing in the file, even if it requires parsing future frames\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR, \fB\-\-silent\fR
.RS 4
Suppresses normal output messages\&.
.RE
.PP
\fB\-Q\fR, \fB\-\-mq\fR
.RS 4
Enable POSIX message queues\&. Set up a communication channel for use with
xjremote(1)\&. See the
the section called \(lqRemote Control Interface\(rq
in the online documentation for more information\&.
.RE
.PP
\fB\-R\fR, \fB\-\-remote\fR
.RS 4
Enable interactive (stdin/stdout) remote control mode\&. Options
\fB\-\-quiet\fR
and
\fB\-\-verbose\fR
have no effect in remote mode\&.
.RE
.PP
\fB\-s\fR, \fB\-\-fullscreen\fR
.RS 4
Start
Xjadeo
in full\-screen mode\&.
.RE
.PP
\fB\-S\fR, \fB\-\-nosplash\fR
.RS 4
Skip the on\-screen\-display startup sequence\&.
.RE
.PP
\fB\-t\fR, \fB\-\-try\-codec\fR
.RS 4
Check if the video file is encoded in a format suitable for use with
Xjadeo
and exit\&. If the video format is not supported the exit code is 1\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Print additional information\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Display version and compile\-time configuration information and exit\&.
.RE
.PP
\fB\-W \fR\fB\fI<rpc\-id>\fR\fR, \fB\-\-ipc \fR\fB\fI<rpc\-id>\fR\fR
.RS 4
Set\-up IPC message queues for
xjremote\&.
\fI<rpc\-id>\fR
specifies a file\-path used to identify the message\-queue\&.
.RE
.PP
\fB\-x \fR\fB\fI<dpy\-mode>\fR\fR, \fB\-\-vo \fR\fB\fI<dpy\-mode>\fR\fR, \fB\-\-videomode \fR\fB\fI<dpy\-mode>\fR\fR
.RS 4
Selects the video output driver\&. Defaults to
\fB0\fR
(auto\-detect)\&. A value of \-1 lists the available modes and exits\&.
.RE
.SH "SYNC SOURCES"
.PP
\fBxjadeo\fR
currently supports the following synchronization sources:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
JACK\-transport\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
LTC (Linear/Longitudinal Time Code) \- via JACK audio\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
MTC (MIDI Time Code) via JACK\-MIDI\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
MTC (MIDI Time Code) via ALSA sequencer\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
MTC (MIDI Time Code) via portmidi\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
remote\-ctrl manual seeks (not really a sync source)\&.
.RE
.SH "VIDEO FORMATS"
.PP
Xjadeo
uses ffmpeg to decode video files, so a wide range of formats and codecs are supported\&. Note, however, that not all the formats support seeking\&. To transcode a video\-file into a suitable format we recommend:
.sp
.if n \{\
.RS 4
.\}
.nf
mencoder \-idx \-ovc lavc \-lavcopts keyint=1 \-nosound input_file\&.xxx \-o output_file\&.avi
.fi
.if n \{\
.RE
.\}
.sp
This creates from your input\-file\&.xxx an AVI mpeg4 encoded video file with no sound, an index (\-idx) and no compression between frames (every frame is a keyframe)\&. The file thus can become really BIG, so watch your disk space!
.PP
You may want also to shrink the size of the file\*(Aqs video frames by scaling down its geometry\&. This uses fewer system resources while decoding and displaying it and leaves more space in the screen for your audio software\&.
.sp
.if n \{\
.RS 4
.\}
.nf
\-vf scale=width:height
.fi
.if n \{\
.RE
.\}
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBImportant\fR
.ps -1
.br
.PP
Also note
Xjadeo\*(Aqs
\fB\-K\fR
option which allows to seek to frames other than key\-frames and enables
Xjadeo
to play back any file without transcoding it\&. It comes at the expense of increased CPU usage and possibly increased seek latency\&. The latter depends on the key\-frame interval and video\-codec\&.
.PP
The same can be achieved by adding
\fBseek=continuously\fR
to
~/\&.xjadeorc\&.
.sp .5v
.RE
.SH "USER INPUT"
.PP
\fBxjadeo\fR
window accepts the following input:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Pressing mouse button 1 will resize the window to the original movie size\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Mouse button 2 and 3 resize the window to match the movie aspect ratio\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Scroll Wheel (buttons 4,5) stepwise decreases/increases the window size maintaining the original aspect ratio\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Xjadeo
≥ v0\&.3\&.8 supports keyboard events\&. Pressing
Esc
and
q
will end the program\&.
f
toggles full\-screen,
a
togglesalways\-on\-top\&. Press
m
to hide mouse cursor\&.
v,
s,
o,
C
and
b
control on\-screen\-display and
l
toggles the letter\-box mode\&. The time\-offset can be modified with
+,
\-,
{,
}
and window\-size with
<,
>,
,,
\&.\&.
SPACE
and
BACKSPACE
can be used to control JACK\-transport\&. See
the section called \(lqMonitor Window - Key bindings\(rq
in the online documentation for a complete list\&.
.RE
.SH "REMOTE MODE"
.PP
When started in remote mode (option
\fB\-R\fR
or
\fB\-\-remote\fR)
Xjadeo
will interactively accept commands and issue responses through its standard input/output mechanism\&.
.PP
Use the remote command
\fBhelp\fR
to get a quick overview of all available commands\&. Please refer to the online documentation for a complete description of the remote commands\&.
.PP
\fBxjadeo \-Q\fR
enables remote control by message\-queues; use
\fBxjremote\fR
to connect\&.
.SH "FILES"
.PP
Xjadeo
reads the following resource configuration files in this order:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
/@SYSCONFDIR@/xjadeorc
(usually
/etc/xjadeorc
or
/usr/local/etc/xjadeorc, which depends on your distribution and on the configuration when
building xjadeo)
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
$HOME/\&.xjadeorc
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
\&./xjadeorc
.RE
.PP
Each line in the configuration file must be in in the format:
.sp
.if n \{\
.RS 4
.\}
.nf
KEY=VALUE
.fi
.if n \{\
.RE
.\}
.sp
If the first character on a line is either
\fB#\fR
or
\fB;\fR
the line is ignored\&.
\fBKEYS\fR
are not case sensitive\&. Some
\fBVALUES\fR
are case sensitive (e\&.g\&. filenames) and are parsed identical to the corresponding command\-line arguments (e\&.g\&.
\fB\-x SDL\fR
is equivalent to the config\-file option
\fBvideomode=SDL\fR)\&. Boolean values are specified as
\fByes\fR
or
\fBno\fR
(e\&.g\&.
\fBquiet=yes\fR)\&.
.PP
currently supported RC\-KEYS: fps, fontfile, lash, letterbox, midiclk, mididriver, midiid, midismpte, mq, nosplash, quiet, seek, verbose and videomode\&. Which are documented in the example
\m[blue]\fBxjadeorc\fR\m[]\&\s-2\u[1]\d\s+2
.SH "ENVIRONMENT"
.PP
\fBJACK_DEFAULT_SERVER\fR
.RS 4
Set the jack\-server\-name to connect to (used by JACK\-transport, JACK\-MIDI and LTC)
.RE
.SH "SEE ALSO"
.PP
qjadeo(1)
.PP
xjremote(1)
.PP
xjinfo(1)
.PP
\m[blue]\fBonline\-manual\fR\m[]\&\s-2\u[2]\d\s+2
.SH "AUTHORS"
.PP
\fBRobin Gareus\fR <\&robin@gareus.org\&>
.RS 4
linuxaudio.org
.RE
.PP
\fBLuis Garrido\fR <\&luisgarrido@users.sourceforge.net\&>
.RS 4
luisgarrido.users.sourceforge.net
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2005, 2006, 2007, 2009, 2010 Robin Gareus, Luis Garrido
.br
.SH "NOTES"
.IP " 1." 4
xjadeorc
.RS 4
\%http://xjadeo.git.sourceforge.net/git/gitweb.cgi?p=xjadeo/xjadeo;a=blob_plain;f=doc/xjadeorc
.RE
.IP " 2." 4
online-manual
.RS 4
\%http://xjadeo.sourceforge.net/
.RE
