.\"     Title: xjinfo
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 05/07/2007
.\"    Manual: Manual Pages
.\"    Source: 
.\"
.TH "XJINFO" "1" "05/07/2007" "" "Manual Pages"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
xjinfo \- Display A/V file info in XML format.
.SH "SYNOPSIS"
.HP 7
\fBxjinfo\fR [\-xvhct] \efI<videofile>\efR
.SH "DESCRIPTION"
.PP
\fBxjinfo\fR
does basically the same as
\fBffmpeg \-i\fR
but displays the information in XML or simple format that can be used for scripting.
.SH "OPTIONS"
.PP
\fB\-c, \-\-csv\fR
.RS 4
comma separated values, one line per video stream in file. Use the built\-in help \-h to learn about the format.
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Prints usage help and exits.
.RE
.PP
\fB\-t, \-\-time, \-\-duration\fR
.RS 4
print the duration in seconds (without trailing newline)
.RE
.PP
\fB\-v, \-\-text\fR
.RS 4
print a single line: duration, fps, geometry and codec info.
.RE
.PP
\fB\-x, \-\-xml\fR
.RS 4
output XML data. This is the default if no option is specified.
.sp
A DTD is available with the source or from
\fIxjadeo.sf.net\fR\&[1]
.RE
.SH "SEE ALSO"
.PP
xjadeo(1)
.SH "COPYRIGHT"
Copyright \(co 2005, 2006, 2007 Robin Gareus, Luis Garrido
.br
.SH "REFERENCES"
.IP " 1." 4
xjadeo.sf.net
.RS 4
\%http://svn.sourceforge.net/viewcvs.cgi/*checkout*/xjadeo/trunk/src/xjadeo/avinfo.dtd
.RE
