.\"     Title: xjinfo
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 11/27/2006
.\"    Manual: Manual Pages
.\"    Source: 
.\"
.TH "XJINFO" "1" "11/27/2006" "" "Manual Pages"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
xjinfo \- Display A/V file info in XML format.
.SH "SYNOPSIS"
.HP 7
\fBxjinfo\fR [\-xvhct] \fI<videofile>\fR
.SH "DESCRIPTION"
.PP
\fBxjinfo\fR
does basically the same as
\fBffmpeg \-i\fR
but displays the information in XML or simple format that can be used for scripting.
.SH "OPTIONS"
.PP
\fB\-c, \-\-csv\fR
.RS 3n
comma separated values, one line per video stream in file. Use the built\-in help \-h to learn about the format.
.RE
.PP
\fB\-h, \-\-help\fR
.RS 3n
Prints usage help and exits.
.RE
.PP
\fB\-t, \-\-time, \-\-duration\fR
.RS 3n
output XML data. This is the default if no option is specified
.RE
.PP
\fB\-v, \-\-text\fR
.RS 3n
print a single line: duration, fps, geometry and codec info.
.RE
.PP
\fB\-x, \-\-xml\fR
.RS 3n
output XML data. This is the default if no option is specified.
.sp
A DTD is available with the source or from
[1]\&\fIxjadeo.sf.net\fR
.RE
.SH "SEE ALSO"
.PP
xjadeo(1)
.SH "COPYRIGHT"
Copyright \(co 2005, 2006 Robin Gareus, Luis Garrido
.br
.SH "REFERENCES"
.TP 3
1.\ xjadeo.sf.net
\%http://svn.sourceforge.net/viewcvs.cgi/*checkout*/xjadeo/trunk/src/xjadeo/avinfo.dtd
