'\" t
.\"     Title: xjinfo
.\"    Author: Robin Gareus <robin@gareus.org>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/24/2010
.\"    Manual: Manual Pages
.\"    Source: http://xjadeo.sf.net 0.6.X
.\"  Language: English
.\"
.TH "XJINFO" "1" "11/24/2010" "http://xjadeo\&.sf\&.net 0\&.6" "Manual Pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xjinfo \- Display A/V file info in XML format\&.
.SH "SYNOPSIS"
.HP \w'\fBxjinfo\fR\ 'u
\fBxjinfo\fR [\-chtvVx] \fI<videofile>\fR
.SH "DESCRIPTION"
.PP
xjinfo
does basically the same as
\fBffprobe\fR
but displays the information in XML or simple text format that can be used for scripting\&.
.SH "OPTIONS"
.PP
\fB\-c\fR, \fB\-\-csv\fR
.RS 4
comma separated values, one line per video stream in file\&. Use the built\-in help
\fB\-h\fR
to learn about the format\&.
.RE
.PP
\fB\-h\fR, \fB\-h, \-\-help\fR
.RS 4
Print usage help and exit\&.
.RE
.PP
\fB\-t\fR, \fB\-\-time\fR, \fB\-\-duration\fR
.RS 4
print the duration in seconds (without trailing newline)
.RE
.PP
\fB\-v\fR, \fB\-\-text\fR
.RS 4
print a single line: duration, fps, geometry and codec info\&.
.RE
.PP
\fB\-x\fR, \fB\-\-xml\fR
.RS 4
output XML data\&. This is the default if no option is specified\&.
.sp
A DTD is available with the source or from
\m[blue]\fBxjadeo\&.sf\&.net\fR\m[]\&\s-2\u[1]\d\s+2
.RE
.SH "SEE ALSO"
.PP
xjadeo(1)
.SH "AUTHORS"
.PP
\fBRobin Gareus\fR <\&robin@gareus.org\&>
.RS 4
linuxaudio.org
.RE
.PP
\fBLuis Garrido\fR <\&luisgarrido@users.sourceforge.net\&>
.RS 4
luisgarrido.users.sourceforge.net
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2005, 2006, 2007, 2009, 2010 Robin Gareus, Luis Garrido
.br
.SH "NOTES"
.IP " 1." 4
xjadeo.sf.net
.RS 4
\%http://xjadeo.git.sourceforge.net/git/gitweb.cgi?p=xjadeo/xjadeo;a=blob_plain;f=src/xjadeo/avinfo.dtd
.RE
