.\"     Title: xjremote
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 05/07/2007
.\"    Manual: Manual Pages
.\"    Source: 
.\"
.TH "XJREMOTE" "1" "05/07/2007" "" "Manual Pages"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
xjremote \- CLI front\-end to xjadeo
.SH "SYNOPSIS"
.HP 9
\fBxjremote\fR [\-fhquUvV]
.SH "DESCRIPTION"
.PP
\fBxjadeo\fR
displays a video clip in sync with an external time source. It is a handy tool to help with the synchronization of the soundtrack of a video file.
.PP
\fBxjremote\fR
connects to a instance of xjadeo and allows a user to tweak the running configuration.
.PP
If it can not connect, xjremote will start a new instance of xjadeo and open a connection to it. see
\fB\-f\fR
.SH "OPTIONS"
.PP
\fB\-f, \-\-nofork\fR
.RS 4
disable automatic startup of xjadeo. Instead xjremote will terminate if it can not connect to a running xjadeo.
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Prints usage help and exits.
.RE
.PP
\fB\-P, \-\-noping\fR
.RS 4
Skip checking for xjadeo live signs (ping).
.RE
.PP
\fB\-q, \-\-quiet, \-\-silent\fR
.RS 4
Suppresses normal output messages.
.RE
.PP
\fB\-R\fR
.RS 4
ignored (no action) \-
\fBxjremote\fR
can be used as a drop in replacement for
\fBxjadeo \-R\fR.
.RE
.PP
\fB\-u, \-\-unlink\fR
.RS 4
remove existing queues. unless combined with
\fB\-f\fR. This will launch always a new xjadeo instance after unlinking the queues. Note: active connections are not affected.
.RE
.PP
\fB\-U, \-\-unlinkonly\fR
.RS 4
remove existing queues and exit. This is equivalent (but not identical) to
\fB\-u \-f\fR.
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Prints additional information during the execution.
.RE
.PP
\fB\-V, \-\-version\fR
.RS 4
Prints version information end exits.
.RE
.SH "ENVIRONMENT"
.PP
If the XJADEO variable is set, xjremote will assume that it holds the path to the xjadeo executable.
.SH "NOTE"
.PP
Xjadeo message queues are experiemental and not completed! With the upcoming introduction of queue\-names or a operation mode that allows multiple clients per connection, xjremote's command line options will change.
.SH "SEE ALSO"
.PP
xjadeo(1)
.PP
qjadeo(1)
.SH "COPYRIGHT"
Copyright \(co 2005, 2006, 2007 Robin Gareus, Luis Garrido
.br

