'\" t
.\"     Title: xjremote
.\"    Author: Robin Gareus <robin@gareus.org>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/24/2010
.\"    Manual: Manual Pages
.\"    Source: http://xjadeo.sf.net 0.6.X
.\"  Language: English
.\"
.TH "XJREMOTE" "1" "11/24/2010" "http://xjadeo\&.sf\&.net 0\&.6" "Manual Pages"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xjremote \- CLI remote\-control to \fBxjadeo\fR
.SH "SYNOPSIS"
.HP \w'\fBxjremote\fR\ 'u
\fBxjremote\fR [\-fhPquUvV] [\-I\ \fI<mq\-queue\-id>\fR]
.SH "DESCRIPTION"
.PP
Xjadeo
is a software video player that displays a video\-clip in sync with an external time source (MTC, LTC, JACK\-transport)\&.
.PP
\fBxjremote\fR
connects to a instance of
Xjadeo
and allows a user to tweak the running configuration\&.
.PP
If it can not connect, xjremote will start a new instance of
Xjadeo
and open a connection to it unless the
\fB\-f\fR
is given\&.
.SH "OPTIONS"
.PP
\fB\-f\fR, \fB\-\-nofork\fR
.RS 4
disable automatic startup of
Xjadeo\&. Instead xjremote will terminate if it can not connect to a running
Xjadeo\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Prints usage help and exits\&.
.RE
.PP
\fB\-I \fR\fB\fI<ipc\-id>\fR\fR, \fB\-\-id \fR\fB\fI<ipc\-id>\fR\fR
.RS 4
specify message\-queue identifier\&.
.RE
.PP
\fB\-P\fR, \fB\-P, \-\-noping\fR
.RS 4
Skip checking for
Xjadeo
life signs (ping)\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR, \fB\-\-silent\fR
.RS 4
Suppresses normal output messages\&.
.RE
.PP
\fB\-Q\fR
.RS 4
ignored \-
xjremote
can be used as a drop in replacement for
\fBxjadeo \-Q\fR\&.
.RE
.PP
\fB\-R\fR
.RS 4
ignored \-
xjremote
can be used as a drop in replacement for
\fBxjadeo \-R\fR\&.
.RE
.PP
\fB\-u\fR, \fB\-\-unlink\fR
.RS 4
remove existing queues\&. Unless combined with
\fB\-f\fR
this will launch always a new
Xjadeo
instance after unlinking the queues\&. Note: active connections are not affected\&.
.RE
.PP
\fB\-U\fR, \fB\-\-unlinkonly\fR
.RS 4
remove existing message queues and exit\&. If no
Xjadeo
instance is running this is equivalent to
\fB\-u \-f\fR\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Print additional information\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Print version information end exit\&.
.RE
.PP
\fB\-W \fR\fB\fI<rpc\-id>\fR\fR
.RS 4
ignored \-
xjremote
can be used as a drop in replacement for
\fBxjadeo \-W \&.\&.\fR\&.
.RE
.SH "ENVIRONMENT"
.PP
If the
\fBXJADEO\fR
variable is set,
xjremote
will assume that it holds the path to the
Xjadeo
executable\&.
.SH "NOTE"
.PP
Apart from Standard\-I/O,
Xjadeo
can either use POSIX real\-time message\-queues (MQ) or System\-V IPC communication\&. The decision is made when compiling it\&. Basically GNU/Linux uses MQ (but could use IPC as well)\&. OSX only supports IPC and Windows is limited to standard\-I/O only\&.
.SH "SEE ALSO"
.PP
xjadeo(1)
.PP
qjadeo(1)
.SH "AUTHORS"
.PP
\fBRobin Gareus\fR <\&robin@gareus.org\&>
.RS 4
linuxaudio.org
.RE
.PP
\fBLuis Garrido\fR <\&luisgarrido@users.sourceforge.net\&>
.RS 4
luisgarrido.users.sourceforge.net
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2005, 2006, 2007, 2009, 2010 Robin Gareus, Luis Garrido
.br
